create command won't use project name for folder #508
enonic/cli-enonic pull request #510
Opened 2024-02-01 16:31 UTC by pmi

2024-02-01 21:28 UTC, alansemenov requested changes
Everything seems to work as expected, but there's a strange new warning that appears now: "`Warning: 'import' is not a valid sandbox folder.`"

<img width="786" alt="image" src="https://github.com/enonic/cli-enonic/assets/11612490/5efbb747-d8b3-4398-bd00-d5e739f14d64">

2024-02-02 08:56 UTC, pmi commented
@alansemenov  
This warning is printed when you have invalid sandbox in your `~/.enonic/sandboxes/` folder.
Try inspecting the `~/.enonic/sandboxes/import` folder for `.enonic` file inside.

2024-02-02 09:19 UTC, alansemenov commented
> This warning is printed when you have invalid sandbox in your `~/.enonic/sandboxes/` folder. Try inspecting the `~/.enonic/sandboxes/import` folder for `.enonic` file inside.

Yep, that was the case

2024-02-02 09:19 UTC, alansemenov approved these changes

2024-02-02 09:20 UTC, merged